// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqbipgnldiljvolwdmaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxYmlwZ25sZGlsanZvbHdkbWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzA3NDcsImV4cCI6MjA1NzcwNjc0N30.GTfvs_Zn4ijhY_yRFqKLivY3C_EaLtPR0nzIRdwcS0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);